paths:
  cat_path: "./data/"
  db_path: null
  mf_path: "./data/"
  umap_path: null

field_name: "gds-grizli-v7.2"
file_names:
  cat_filename: "gds-grizli-v7.2-fix_phot_apcorr.fits"
  db_filename: null
  mf_filename: "gds_grizli-v7.2_dja-v7.2_catalog.csv"
  umap_filename: null
flag_file_name: "ingest_flags.fits"

version: "v1.0"
output_path: "./output/"

columns_to_use:
  cat_filename:
    - "id"
    - "ra"
    - "dec"
    - "flux_radius"
    - "abmag_f435w"
    - "abmag_f475w"
    - "abmag_f606w"
    - "abmag_f775w"
    - "abmag_f814w"
    - "abmag_f090w"
    - "abmag_f105w"
    - "abmag_f110w"
    - "abmag_f115w"
    - "abmag_f115wn"
    - "abmag_f125w"
    - "abmag_f140w"
    - "abmag_f150w"
    - "abmag_f150wn"
    - "abmag_f160w"
    - "abmag_f162m"
    - "abmag_f182m"
    - "abmag_f200w"
    - "abmag_f200wn"
    - "abmag_f210m"
    - "abmag_f250m"
    - "abmag_f277w"
    - "abmag_f300m"
    - "abmag_f335m"
    - "abmag_f356w"
    - "abmag_f410m"
    - "abmag_f430m"
    - "abmag_f444w"
    - "abmag_f460m"
    - "abmag_f480m"
    - "abmag_f560w"
    - "abmag_f770w"
    - "abmag_f1000w"
    - "abmag_f1280w"
    - "abmag_f1500w"
    - "abmag_f1800w"
    - "abmag_f2100w"
    - "abmag_f850lp"
  mf_filename:
    - "id"
    - "f090w-clear-use"
    - "f090w-clear-chi"
    - "f090w-clear-sb"
    - "f090w-clear-reff"
    - "f090w-clear-sersic"
    - "f090w-clear-axratio"
    - "f115w-clear-use"
    - "f115w-clear-chi"
    - "f115w-clear-sb"
    - "f115w-clear-reff"
    - "f115w-clear-sersic"
    - "f115w-clear-axratio"
    - "f150w-clear-use"
    - "f150w-clear-chi"
    - "f150w-clear-sb"
    - "f150w-clear-reff"
    - "f150w-clear-sersic"
    - "f150w-clear-axratio"
    - "f182m-clear-use"
    - "f182m-clear-chi"
    - "f182m-clear-sb"
    - "f182m-clear-reff"
    - "f182m-clear-sersic"
    - "f182m-clear-axratio"
    - "f200w-clear-use"
    - "f200w-clear-chi"
    - "f200w-clear-sb"
    - "f200w-clear-reff"
    - "f200w-clear-sersic"
    - "f200w-clear-axratio"
    - "f210m-clear-use"
    - "f210m-clear-chi"
    - "f210m-clear-sb"
    - "f210m-clear-reff"
    - "f210m-clear-sersic"
    - "f210m-clear-axratio"
    - "f250m-clear-use"
    - "f250m-clear-chi"
    - "f250m-clear-sb"
    - "f250m-clear-reff"
    - "f250m-clear-sersic"
    - "f250m-clear-axratio"
    - "f277w-clear-use"
    - "f277w-clear-chi"
    - "f277w-clear-sb"
    - "f277w-clear-reff"
    - "f277w-clear-sersic"
    - "f277w-clear-axratio"
    - "f300m-clear-use"
    - "f300m-clear-chi"
    - "f300m-clear-sb"
    - "f300m-clear-reff"
    - "f300m-clear-sersic"
    - "f300m-clear-axratio"
    - "f335m-clear-use"
    - "f335m-clear-chi"
    - "f335m-clear-sb"
    - "f335m-clear-reff"
    - "f335m-clear-sersic"
    - "f335m-clear-axratio"
    - "f356w-clear-use"
    - "f356w-clear-chi"
    - "f356w-clear-sb"
    - "f356w-clear-reff"
    - "f356w-clear-sersic"
    - "f356w-clear-axratio"
    - "f410m-clear-use"
    - "f410m-clear-chi"
    - "f410m-clear-sb"
    - "f410m-clear-reff"
    - "f410m-clear-sersic"
    - "f410m-clear-axratio"
    - "f430m-clear-use"
    - "f430m-clear-chi"
    - "f430m-clear-sb"
    - "f430m-clear-reff"
    - "f430m-clear-sersic"
    - "f430m-clear-axratio"
    - "f444w-clear-use"
    - "f444w-clear-chi"
    - "f444w-clear-sb"
    - "f444w-clear-reff"
    - "f444w-clear-sersic"
    - "f444w-clear-axratio"
    - "f460m-clear-use"
    - "f460m-clear-chi"
    - "f460m-clear-sb"
    - "f460m-clear-reff"
    - "f460m-clear-sersic"
    - "f460m-clear-axratio"
    - "f480m-clear-use"
    - "f480m-clear-chi"
    - "f480m-clear-sb"
    - "f480m-clear-reff"
    - "f480m-clear-sersic"
    - "f480m-clear-axratio"
