paths:
  cat_path: "./data/"
  db_path: null
  mf_path: null
  umap_path: null

field_name: "gds-grizli-v7.2"
file_names:
  cat_filename: "gds-grizli-v7.2-fix_phot_apcorr.fits"
  db_filename: null
  mf_filename: null
  umap_filename: null

version: "v1.0"
output_path: "./output/"

columns_to_use:
  cat_filename:
    - "id"
    - "ra"
    - "dec"
    - "flux_radius"
    - "abmag_f435w"
    - "abmag_f475w"
    - "abmag_f606w"
    - "abmag_f775w"
    - "abmag_f814w"
    - "abmag_f090w"
    - "abmag_f105w"
    - "abmag_f110w"
    - "abmag_f115w"
    - "abmag_f115wn"
    - "abmag_f125w"
    - "abmag_f140w"
    - "abmag_f150w"
    - "abmag_f150wn"
    - "abmag_f160w"
    - "abmag_f162m"
    - "abmag_f182m"
    - "abmag_f200w"
    - "abmag_f200wn"
    - "abmag_f210m"
    - "abmag_f250m"
    - "abmag_f277w"
    - "abmag_f300m"
    - "abmag_f335m"
    - "abmag_f356w"
    - "abmag_f410m"
    - "abmag_f430m"
    - "abmag_f444w"
    - "abmag_f460m"
    - "abmag_f480m"
    - "abmag_f560w"
    - "abmag_f770w"
    - "abmag_f1000w"
    - "abmag_f1280w"
    - "abmag_f1500w"
    - "abmag_f1800w"
    - "abmag_f2100w"
    - "abmag_f850lp"
