paths:
  cat_path: "./data/"
  db_path: "./data/"
  mf_path: "./data/"
  umap_path: null

field_name: "ngdeep-grizli-v7.2"
file_names:
  cat_filename: "ngdeep-grizli-v7.2-fix_phot_apcorr.fits"
  db_filename: "ngdeep_v7.2_DB_catalog_small.cat"
  mf_filename: "ngdeep_grizli-v7.2_dja-v7.2_catalog.csv"
  umap_filename: null
flag_file_name: "ingest_flags.fits"

version: "v1.0"
output_path: "./output/"

columns_to_use:
  cat_filename:
    - "id"
    - "ra"
    - "dec"
    - "flux_radius"
    - "abmag_f435w"
    - "abmag_f475w"
    - "abmag_f606w"
    - "abmag_f775w"
    - "abmag_f814w"
    - "abmag_f105w"
    - "abmag_f115w"
    - "abmag_f125w"
    - "abmag_f140w"
    - "abmag_f150w"
    - "abmag_f160w"
    - "abmag_f200w"
    - "abmag_f277w"
    - "abmag_f356w"
    - "abmag_f444w"
    - "abmag_f350lpu"
    - "abmag_f850lp"
  db_filename:
    - "id"
    - "zfit_50"
    - "logM_50"
    - "logSFRinst_50"
    - "logZsol_50"
    - "Av_50"
    - "logMt_50"
    - "logSFR10_50"
    - "logSFR100_50"
    - "logSFR300_50"
    - "logSFR1000_50"
    - "t25_50"
    - "t50_50"
    - "t75_50"
    - "chi2"
    - "fit_flags"
    - "nbands"
  mf_filename:
    - "id"
    - "f115w-clear-use"
    - "f115w-clear-chi"
    - "f115w-clear-sb"
    - "f115w-clear-reff"
    - "f115w-clear-sersic"
    - "f115w-clear-axratio"
    - "f150w-clear-use"
    - "f150w-clear-chi"
    - "f150w-clear-sb"
    - "f150w-clear-reff"
    - "f150w-clear-sersic"
    - "f150w-clear-axratio"
    - "f200w-clear-use"
    - "f200w-clear-chi"
    - "f200w-clear-sb"
    - "f200w-clear-reff"
    - "f200w-clear-sersic"
    - "f277w-clear-use"
    - "f277w-clear-chi"
    - "f277w-clear-sb"
    - "f277w-clear-reff"
    - "f277w-clear-sersic"
    - "f277w-clear-axratio"
    - "f356w-clear-use"
    - "f356w-clear-chi"
    - "f356w-clear-sb"
    - "f356w-clear-reff"
    - "f356w-clear-sersic"
    - "f356w-clear-axratio"
    - "f444w-clear-use"
    - "f444w-clear-chi"
    - "f444w-clear-sb"
    - "f444w-clear-reff"
    - "f444w-clear-sersic"
    - "f444w-clear-axratio"